version: '3.8'

services:
  frontend:
    build: .
    container_name: horizon-blog-fe
    ports:
      - "3000:3000"
    environment:
      - BE_HOST=${BE_HOST}
    networks:
      - horizon-blog

networks:
  horizon-blog:
    driver: bridge
    name: horizon-blog
